// Automatically generated by the DDlog compiler.
package ddlog.analyze;
public final class analyzeRelation
{
    public static final int Edge = 0;
    public static final int Next = 1;
    public static final int Node = 2;
}