// Automatically generated by the DDlog compiler.
package ddlog.analyze;
import com.google.flatbuffers.*;
public final class EdgeReader
{
    protected EdgeReader(ddlog.__analyze.Edge inner) { this.inner = inner; }
    private ddlog.__analyze.Edge inner;
    public java.math.BigInteger from ()
    {
        return new java.math.BigInteger(this.inner.from().sign() ? 1 : -1, analyzeUpdateParser.byteBufferToArray(this.inner.from().bytesAsByteBuffer()));
    }
    public java.math.BigInteger to ()
    {
        return new java.math.BigInteger(this.inner.to().sign() ? 1 : -1, analyzeUpdateParser.byteBufferToArray(this.inner.to().bytesAsByteBuffer()));
    }
}