// Automatically generated by the DDlog compiler.
package ddlog.analyze;
import com.google.flatbuffers.*;
public final class NextReader
{
    protected NextReader(ddlog.__analyze.Next inner) { this.inner = inner; }
    private ddlog.__analyze.Next inner;
    public java.math.BigInteger v ()
    {
        return new java.math.BigInteger(this.inner.v().sign() ? 1 : -1, analyzeUpdateParser.byteBufferToArray(this.inner.v().bytesAsByteBuffer()));
    }
    public java.math.BigInteger nxt ()
    {
        return new java.math.BigInteger(this.inner.nxt().sign() ? 1 : -1, analyzeUpdateParser.byteBufferToArray(this.inner.nxt().bytesAsByteBuffer()));
    }
}