// Automatically generated by the DDlog compiler.
package ddlog.analyze;
import com.google.flatbuffers.*;
public final class Tuple0Reader
{
    protected Tuple0Reader(ddlog.__analyze.Tuple0 inner) { this.inner = inner; }
    private ddlog.__analyze.Tuple0 inner;
}