// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__analyze;

public final class __Value {
  private __Value() { }
  public static final byte NONE = 0;
  public static final byte Edge = 1;
  public static final byte Next = 2;
  public static final byte Node = 3;
  public static final byte Tuple0 = 4;

  public static final String[] names = { "NONE", "Edge", "Next", "Node", "Tuple0", };

  public static String name(int e) { return names[e]; }
}

